---
exclude: .*/README.md
repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.89.0
    hooks:
      - id: terraform_fmt
      - id: terraform_docs
        args:
          - --hook-config=--path-to-file=README.md        # Valid UNIX path. I.e. ../TFDOC.md or docs/README.md etc.
          - --hook-config=--add-to-existing-file=true     # Boolean. true or false
          - --hook-config=--create-file-if-not-exist=true # Boolean. true or false
          - --hook-config=--use-standard-markers=true     # Boolean. Defaults in v1.x to false.
          - --args=--config=terraform/.terraform-docs.yaml
      - id: terraform_tflint
        args:
          - --args=--module
          - --args=--enable-rule=terraform_documented_variables

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-merge-conflict
      - id: check-json
      - id: detect-private-key
      - id: check-added-large-files
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-executables-have-shebangs

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - exclude: ^(.*)\/README\.md$
        id: detect-secrets

  - repo: local
    hooks:
      - args:
          - .
        entry: yamllint
        id: yamllint
        language: system
        name: Check yaml format
        pass_filenames: false
        types:
          - file

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.24.0
    hooks:
      - id: commitizen
...
