---
exclude: '.*/README.md'

repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.74.1
    hooks:
      - id: terraform_fmt
      - id: terraform_docs
        args:
          - "--hook-config=--path-to-file=README.md"
          - "--hook-config=--add-to-existing-file=true"
          - "--hook-config=--create-file-if-not-exist=true"
          - '--args=--escape=false'
          - '--args=--lockfile=false'
          - '--args=--indent 3'
          - '--args=--show all'

      - id: terraform_tflint
        args:
          - '--args=--only=terraform_deprecated_interpolation'
          - '--args=--only=terraform_module_pinned_source'


  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-merge-conflict
      - id: check-json
      - id: detect-private-key
      - id: check-added-large-files
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-executables-have-shebangs

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        exclude: '^(.*)\/README\.md$'

  - repo: local
    hooks:
      - id: yamllint
        name: Check yaml format
        entry: yamllint
        args: ["."]
        pass_filenames: false
        language: system
        types: [file]
...
