---

resources:
  - name: code
    type: git
    source:
      uri: https://github.com/cdelgehier/test-stack.git
      branch: master

jobs:
  - name: linting
    plan:
      - get: code
        trigger: true

      - task: linting
        file: code/.ci/linting.yml

      - task: docs
        file: code/.ci/docs.yml

...
