---

resources:
  - name: code
    type: git
    source:
      uri: https://github.com/cdelgehier/test-stack.git
      branch: master

jobs:
  - name: linting
    plan:
      - get: code
        trigger: true

      - task: linting
        config:
          platform: linux
          image_resource:
            type: registry-image
            source: {repository: python/3.12-slim}
          inputs:
            - name: code
          run:
            path: bash
            args:
              - -ce
              - |
                apt-get update -qq -y
                apt install -qq -y yamllint
                yamllint .


...
